reverting to original feedstock rendering
buijennifer/event-model-feedstock pull request #11
Opened 2019-07-15 21:12 UTC by buijennifer

Restoring feedstock files to match templates from conda smithy repo

2019-07-15 21:42 UTC, mrakitin requested changes
The first successful build before my suggested changes generated this set of packages, even before this PR is merged:
![image](https://user-images.githubusercontent.com/13209176/61251112-88ab4680-a727-11e9-8970-979fdd8cd340.png)

Please apply the suggestion and we will see that no new packages are uploaded with the changes from the review.

2019-07-15 21:42 UTC, mrakitin commented on recipe/meta.yaml
>    script: python setup.py install --single-version-externally-managed --record=record.txt
[Conda-forge docs](https://conda-forge.org/docs/maintainer/adding_pkgs.html?highlight=pip%20install#optional-bld-bat-and-or-build-sh) suggest using pip instead:
```suggestion
   script: "{{ PYTHON }} -m pip install . --no-deps -vv"
```

2019-07-16 15:18 UTC, buijennifer commented
The latest builds were not upload because the package was already uploaded to anaconda.org.

https://dev.azure.com/buijennifer/nsls2/_build/results?buildId=197&view=logs&jobId=4f922444-fdfe-5dcf-b824-02f86439ef14&taskId=937c195f-508d-5135-dc9f-d4b5730df0f7&lineStart=649&lineEnd=650&colStart=1&colEnd=1

2019-07-16 16:56 UTC, mrakitin approved these changes
Thanks for the update.

2019-07-16 16:57 UTC, merged